definitions:
  parser.Transaction:
    properties:
      from:
        type: string
      to:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /block/current:
    get:
      description: Get the latest parsed block
      produces:
      - application/json
      responses:
        "200":
          description: A map where the key is 'currentBlock' and the value is the
            block number
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Get current block
  /subscribe/{address}:
    post:
      description: Subscribe to notifications for incoming/outgoing transactions for
        a specific Ethereum address
      parameters:
      - description: Ethereum address to subscribe to
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A map where the key is 'subscribed' and the value is a boolean
            indicating success
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Address is required
          schema:
            type: string
        "409":
          description: Already subscribed
          schema:
            type: string
      summary: Subscribe given an address
  /transactions/{address}:
    get:
      description: Retrieve inbound and outbound transactions for a subscribed Ethereum
        address
      parameters:
      - description: Ethereum address to retrieve transactions for
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/parser.Transaction'
            type: array
        "400":
          description: Address is required
          schema:
            type: string
      summary: Get transactions given an address
swagger: "2.0"
